### PR TITLE
Add partial Aenea support for Caster

### PR DESCRIPTION
**Pull request by Danesprite**
Re: #312.

This works using a new 'use_aenea' setting, set to false by default. If it is set to true, Aenea's `Key`, `Text` and `Mouse` actions will be used instead of dragonfly's. Aenea's `ProxyAppContext` class will also be imported as `AppContext`, as the two have compatible arguments.

To keep this clean, I've modified dragonfly imports for `Key`, `Text` and `Mouse` to import from `caster.lib.actions` and `dragonfly.AppContext` to be imported from `caster.lib.context`. I've not changed a few grammars like Dragon and Explorer which shouldn't use proxy actions/contexts.

If Aenea is unavailable, an error message will be printed and Caster will fallback on dragonfly's actions and context classes.

Let me know if there are any changes I should make. I don't think this should be merged just yet because I'd like to add what @tbenst suggested [here](https://github.com/synkarius/caster/issues/312#issuecomment-435262251).

### CODE REVIEW

**Comment by esc123** [comment]
Successfully installed caster feat aenea support. Many of the caster commands tested work as expected with the exception of all caster/lib/ccr grammars. None of the commands from theses grammars seem to be registering with aenea and hence are not being executed on the Linux host machine.

**Comment by Danesprite** [comment]
Thanks for installing and testing this. The ccr grammars do work for me. Maybe there is some difference in our Aenea client/server configuration?

**Comment by Danesprite** [comment]
So I noticed that Caster's clipboard related commands (e.g. "stoosh", "spark", "jump in", etc ) won't work properly unless you have something like VirtualBox's shared clipboard functionality enabled. This is not really ideal if you are not using VirtualBox or virtualisation at all, so I'll see if I can get those commands working via the [magneto copypaste yapsy plugin](https://github.com/tbenst/magneto-host/blob/master/server/linux_x11/plugins/copypaste.py).

**Comment by esc123** [comment]
I systematically tested all commands in the caster quick ref guide and all work as expected except any command to do with equals. "equals" is regestered in the VM as a command but does nothing in the host. "greater equal" just prints the '=' but not the '>' part. Likewise less equal prints the '=' but not the '<'. 'equals to' is regestered int he VM as <equals two> and '2' is printed on the host machine. All other commands on the  quick ref guide work well. Im going to investigate the CCR commands a little further now and report back.

**Comment by esc123** [comment]
I uninstalled my caster/aenea version from my VM and replaced it with the current Caster version downloadable from github. I then installed my own CCR scripts and tested them out. All CCR commands were working and the enable/disable commands were also working for all CCR files. However, I switched back to my previous caster/aenea version and these same CCR commands are not working or registering. So it's not that aenea is not picking up the CCR commands but rather they are not being executed by this caster branch for some reason. Ill try reinstalling this branch later and see how it goes.

**Comment by Danesprite** [comment]
Thanks for checking that so thoroughly! I did some digging and discovered that "equals" is not working properly because there is no key translation from "equals" to "equal" in [x11_xdotool.py](https://github.com/dictation-toolbox/aenea/blob/master/server/linux_x11/x11_xdotool.py#L92), so xdotool just ignores the key. A translation is also missing in [x11_libxdo.py](https://github.com/dictation-toolbox/aenea/blob/master/server/linux_x11/x11_libxdo.py#L91). There might be similar problems with "<" and ">". `Text` also translates "=" as "equal", which is one reason why no one has caught this before. I'll make an issue and pull request to fix those Aenea bugs tomorrow.

Okay then, let me know how it goes.

**Comment by esc123** [comment]
Just to give an update on progress, I reinstalled aenea/caster branch again and tested the ccr grammars in the VM and everything is working as expected. 

On a side note I suspect that somehow the .pylintrc file was deleted in my previous caster installation causing my previous problems because that is the only way I could recreate the same behaviour i.e., most core caster commands still working but unable to enable or use CCR grammars.

But when I reinstalled the aenea/caster branch, another problem occurred. That is no commands are getting through to the host machine through the aenea network. I reinstalled aenea again thinking it was a problem on that side but that didn't make a difference. I confirmed that my aenea install is working correctly because the test scripts provided (_hello_world_aenea.py etc.) are behaving as expected when placed in the Dragonfly directory and executed.

So now I have a caster/aenea branch that is fully functional in the VM and a fully functional aenea installation confirmed by those test scripts but for some reason when I execute caster commands in the host machine, the commands are registering in the VM but nothing is going through to the host. Can you think of any reason why your caster/aenea branch wouldnt interact with a working Aenea install? Either way I'm going to have to do some further experimenting.

**Comment by Danesprite** [comment]
@esc123 I've updated Aenea on my Windows guest and host and this branch is working correctly for me.

If you've changed your Aenea host/port configuration in aenea.json, look for a file called server_state.json in your user directory (and in C:\NatLink\NatLink\MacroSystem if your user directory is different) and check if it is also up-to-date. I had a similar problem with Aenea's dictation client where it was using the default values `'host': 'localhost', 'port': 8240` because that file had a mistake in it. Sorry you're having these problems, Aenea can be a pain to set up unfortunately :(

**Comment by esc123** [comment]
Thanks for the feedback but unfortunately I still haven't resolved the issue. I ensured that the host/port settings are identical in the config.py in the server side and the aenea.json and the server_state .json in the client side. I have redone the aenea install instructions multiple times and ensured all three aenea test scripts are working as expected but still no caster commands are being transferred to the host. I also ensured the correct branch of caster is installed by observing the unique import statements for Key and Text classes and everything is as it should be. At this point Im thinking of creating a new VM and reinstalling everything and seeing if that works. Thanks again for the suggestions.

**Comment by tbenst** [comment]
Sorry to hear that. Last trick I can think of is to use the actual IP for host, eg “192.168.56.1“, and playing with your virtualbox network settings (can report what mine are later). I also vaguely remember a bunch of mucking around with netstat to make sure firewall settings / resolution issues weren’t messing things up. I also presume you’ve already done “pip2 install jsonrpclib yapsy subprocess32” given that you’re not reporting any error messages.

**Comment by esc123** [comment]
Decided to bite the bullet and start from scratch with a new VM and fresh install of Windows. Spent much of today reinstalling everything. Executing all Aenea test scripts, all behaved as expected except the last one, _hello_world_aenea. It's giving a ValueError message in the natlink window referring to an invalid \escape in the Python27\Lib\json\decoder.py. The full error is rather lengthy but that is the last line. Didnt get this error in previous installs but I notice when I downloaded Natlink they have a new version out 'Whiskey'. Anyone else get this issue?

**Comment by esc123** [comment]
@tbenst thanks, I tried what you suggested but to no avail. I hadn't done your pip2 install command but didn't make a difference. Thanks anyway!

**Comment by Danesprite** [comment]
@esc123 Sorry you had to go through that again. I don't get that error using Natlink 4.1 whiskey. I'm using jsonrpclib version 0.1.7 and json version 2.0.9 (built-in) if that helps. Maybe you can use [pastebin.com](https://pastebin.com) if the error is very long?

**Comment by Danesprite** [comment]
So I figured the simplest way to allow Caster's clipboard-related commands to work server-side was to subclass and override `dragonfly.Clipboard` when `"use_aenea"` is set to true. The new subclass uses the `copy` and `paste` RPC functions if they are available on the aenea server.

I've adjusted importing of `Clipboard` in 3 files to use `from caster.lib.clipboard import Clipboard` instead. I'm happy to move that somewhere else if it makes more sense.

I still need to add some documentation. Is there any preference for where a new file should be created under caster/doc?

The relevant server plugin files are part of  [tbenst/magento-host](https://github.com/tbenst/magneto-host/tree/master/server/linux_x11/plugins). Unfortunately the way that plugin implements `paste()` using `xsel` doesn't seem to set the clipboard properly for me and can lead to errors.

**Comment by Danesprite** [comment]
@LexiconCode Okay then, will do :+1:

I have the copypaste plugin working using `pyperclip` instead. I couldn't seem to import `pyperclip` in the plugin file. I get [this error](https://stackoverflow.com/questions/36247420/please-change-all-occurrences-of-import-gobject-to-from-gi-repository-import) for some reason (the solution didn't work for me). Executing `pyperclip` as a script instead through `subprocess` does work. It requires version 1.7.0 I think. See [copypaste.py]( https://github.com/Danesprite/magneto-host/blob/master/server/linux_x11/plugins/copypaste.py) in my fork of magneto-host.

@tbenst I can make a pull request to magneto-host with the changes if you like. I've tested it and the plugin will also work on MacOS this way, just need to set `PLUGIN_PATH` in the osx config and have yapsy installed too. I swapped the function names to use what pyperclip uses to avoid confusion.

**Comment by Danesprite** [comment]
I've added some documentation and adjusted the `Clipboard` subclass to work properly with my `pyperclip` version of the copypaste plugin.

I'd say this is ready for merging now. The "stoosh [\<n\>]]" and "spark [\<n\>]" commands work perfectly for me now with n >= 1. The "jump in/out" commands also seem to work, although they are pretty slow. It also works as expected when `use_aenea` is false.

@esc123 If you're still having trouble with this, I could try to help you via screen sharing or something if you like :-)

**Comment by esc123** [comment]
@Danesprite thanks for the offer. I have put my aenea install project on hold for the past week or so with other life stuff going on. I'm going to take another crack at it between today and tomorrow to see if I can get it working (and to make sure I haven't done or omitted anything silly that's causing the problem). If I haven't got it working by tomorrow I might just take you up on that offer. Thanks again!

**Comment by Danesprite** [comment]
@esc123 Okay then. No problem :+1:

**Comment by LexiconCode** [comment]
A quick test before I resolved conflicts. 
```
Ignoring ccr rule 'Punctuation'. Failed to load with: 
name 'Choice' is not defined
Ignoring application 'sublime'. Failed to load with: 
name 'Repeat' is not defined
```

**Comment by esc123** [comment]
@Danesprite There definitely seems to be something up with my fresh VM install with Natlink Whiskey from last week. I reinstalled your caster-aenea branch into my dragonfly directory just now and started up dragon and got the following error straight off the bat in the natlink window https://pastebin.com/siJz5Qcw

Not sure where to start with troubleshooting bar a fresh install of Natlink to double check I have all dependencies installed correctly. I thought I'd cross with you before doing so just in case you have a better suggestion. And I haven't even touched Aenea yet! :)

**Comment by Danesprite** [comment]
@esc123 @LexiconCode Thanks for pointing those out. I've fixed those and a few other import errors. I noticed the "drop" command wasn't working, so I fixed that too.

**Comment by esc123** [comment]
@Danesprite that's fantastic. That solved the reported errors. I continued on with the Aenea install and successfully executed the '_hello_world_aenea.py' test script whereby 'Aenea remote setup operational' is printed on the server side. However, although your Aenea/Caster branch is installed, Caster commands are still not being transferred to the server, instead they are just being executed in the client. The server/host settings are identical on both server/client and I have set "use_aenea" to True in the settings.py file. I have a bad feeling I'm missing something relatively straightforward but I just can't see it.

**Comment by tbenst** [comment]
@Danesprite sure please do make a pull request and I’ll test on Ubuntu.

**Comment by Danesprite** [comment]
@esc123 Well it's good Aenea is working for you now. Does "Unable to import aenea actions" appear in the messages window? What Caster commands are you testing with?

@tbenst I've made a pull request to magneto-host. The uses of the plugin's `copy` and `paste` functions also need to be swapped in magneto-client for it to work.

**Comment by Danesprite** [comment]
Somewhat unrelated to this, but I've just fixed a bug in `drop_keep_clipboard` and simplified it a little.

This should be ready for merging now. The configuration issue @esc123 was having is resolved now. It is also working for @LexiconCode.

**Comment by Versatilus** [comment]
I'm sorry for the merge conflicts. If I had been paying attention I would have merged this first, then dealt with the merge conflicts on my end. As soon as I notice this has been fixed, I'll be sure to merge it promptly.

**Comment by Versatilus** [comment]
Nevermind. I fixed it myself. I then also broke it myself… It's a good thing it's an easy fix.

**Comment by Danesprite** [comment]
@Versatilus No problem :-) Thanks for merging this :+1:

**Comment by tbenst** [comment]
Great work @Danesprite!

**Comment by esc123** [comment]
@Danesprite Thanks again for your work making Caster Aenea compatible and for your help getting mine up and running!

**Comment by Danesprite** [comment]
@tbenst @esc123 Thanks, no problem :-)

**Pull request merged**
