### PR TITLE
Extra r commands

### PR DESCRIPTION
**Pull request by Digital-ecologist**
Hi. Since there's active work going on related to r.py I thought I'd submit the few commands I've added so far, in case there helpful to others. Hopefully I've done everything correctly. All I've done is added the tail command for consistency, (since head already existed) and then added support for the pacman package toward the bottom. If anything else is changed, it's unintentional. Let me know if I've made any errors as this is my first pull request. Feedback is welcome.

### CODE REVIEW

**Comment by LexiconCode** [comment]
Excellent work @Digital-ecologist. Although we might want to merge 'Cleaning up the R module #283' first then evaluate your pull request since edit the same files.

**Comment by mrob95** [comment]
This looks good. I've gone ahead and added it to my PR along with a docs update.

**Comment by LexiconCode** [comment]
@mrob95 Digital-ecologist loose the credit for his pull rest and code. So you guys will need to navigate the best course of action.

**Comment by LexiconCode** [comment]
@Digital-ecologist 'cleaning up the R module' is merged. if you want to make any further enhancements you can.

**Comment by Digital-ecologist** [comment]
Thanks for the info. As mrob95 was kind enough to implement all my initial additions during 'cleaning up the R module', I don't have anything to add right now. Over the next couple of weeks, I'll be doing a lot of work with lme4, but I don't have my mind wrapped around whether or not it makes sense to add more lme4 commands, or how best to that yet.

**Comment by LexiconCode** [comment]
Sounds good I will close the issue. Looking forward to see what you come up with next!

**Pull request closed without merging**
