### PR TITLE
Legion Enhancement, Cheat sheet update, and more

### PR DESCRIPTION
**Pull request by LazoCoder**
- Fixed Issue #194 
  - Users can now have multiple versions of python installed and not encounter issues with grid systems & asynch tasks (specifically if their environment variables point to a different python version).
- Significantly enhanced legion's ability to find text with no noticeable difference in speed
  - I experienced issues with the prior implementation of legion where faded out font was ignored and also certain font and background color combinations would throw off the algorithm. This is no longer a problem.
legion
- Added "bench" and "squat" which perform "left mouse button down" and "left mouse button up" functions respectively.
  - This is for users who use mouse equipment such as the [SmartNav](https://www.naturalpoint.com/smartnav/) and desire the ability to drag.
  - I chose the words "bench" and "squat" because they are simple, crisp, single syllable words that are related to each other by definition. They are also related to "kick" since they are all athletic movements (easier to remember).
  - I've been using "bench" and "squat" now for a few weeks and haven't had any issues with dragon confusing it with any other words (I'm North American and don't speak with any discernible accent as far as I am aware).
- Updated the Cheat Sheet
  - (3) corrected “at sign” to “atty”
  - (4) wally
  - (7) bench, squat
  - (9) window snapping

Tested and working fine on my bootcamp installation of Windows 10 on my 15" Mac Book Pro (2015), using Dragon v14.

### CODE REVIEW

**Comment by chilimangoes** [comment]
Nice work indeed! The one observation I would make is that, at least for me, "squat" would be more intuitive as the mouse down command since I think of squatting down. But it's also not a big deal if you prefer to keep it the way it is.

**Comment by LazoCoder** [comment]
@chilimangoes Sure, that makes more sense. I'll change it.
@gerrish Can you be more specific? Is it [this](https://github.com/LazoCoder/caster/blob/b0356009fd701f49529f29b6ac7756701730d404/caster/asynch/mouse/legion.py#L133) line you want changed? What is the error that you get?

**Comment by LazoCoder** [comment]
I've switched the functionality of bench and squat. Additionally, I've successfully broken down legions rectangles in *another branch* (as per #126). Here is what it looks like:
split_1
The question is what to do with legion's "light" command. How often do you guys use this? I can remove it, or leave it in, but keep in mind if I leave it in it will now highlight a smaller region. I haven't used it enough to gauge the usefulness of this so any pointers are appreciated.

Alternatively I can leave the original unbroken down rectangle but have it in a different color. This could be used for a greater highlighting area. See the following image to understand what I mean. I made this in Microsoft paint, the three blue rectangles can be used if the user wants to highlight more content than what the smaller rectangles would allow. The number would be on either the right or left side. So for example the user could say "111 light" and it would select 107, 108, 109 and 110 (the whole area).
split_2
But maybe this will look clustered, ugly or confusing for new users? If the highlight command is seldom used then it may not be worth it to add this complexity to both the code and the screen. I haven't implemented this part yet so let me know what you think before I do.

**Comment by chilimangoes** [comment]
I've rarely the "light" command. Personally, I would vote for leaving it how it is, with the option of maybe modifying it later to do something like "light one hundred and forty through one hundred and forty four." That shouldn't be hard to implement and would give us the best of both worlds.

**Comment by Versatilus** [comment]
@gerrish This is mostly my fault. I'm guessing that in this case the library loader requires a byte string for the path because of ctypes issues. This should be easily fixed by encoding the Unicode string to a byte string based on the file system locale.

**Comment by LazoCoder** [comment]
Okay so I went ahead and I added in the rectangle division as demonstrated in my previous comment. I left the highlight function as it is.

Furthermore I had an issue where every time I said "again x times" a console would pop up and start printing things to the screen and preventing the function from occurring. This has been fixed.

I won't be adding anything more to this branch so you guys can test it. If there are any issues that you want me to fix let me know.

**Comment by LazoCoder** [comment]
I ran a recursive command to convert all the files to yapf as per the .style.yapf file.
> C:/Python27/scripts/yapf -i -r --style .style.yapf -vv *

**Comment by Versatilus** [comment]
I love this!

**Pull request merged**
