### PR TITLE
Refactor Apps directory

### PR DESCRIPTION
**Pull request by LexiconCode**
The refactoring Apps is motivated because applications have more than one supporting .py or multiple grammars. This change keeps applications organized as each application grow in the number of supporting grammars. In addition the structural change allows for users to copy individual apps directorys and all their sub supporting files over to the user directory. Thus applications that have more than one .py have been moved into the their own directory. 

WIP as I'm not sure why the loader despite having `__init__.py` in each subdirectory complains about missing 'get_rule' when Caster loads.

> No method named 'get_rule' was found on 'vscode'. Did you forget to implement it?
No method named 'get_rule' was found on 'eclipse'. Did you forget to implement it?
No method named 'get_rule' was found on 'dragon'. Did you forget to implement it?
No method named 'get_rule' was found on 'totalcmd'. Did you forget to implement it?
Skipping rule DragonRule because it is enabled but not loaded.

Unit tests pass with updated imports

### CODE REVIEW

**Comment by synkarius** [comment]
Do those rules which print that error still work?

**Comment by synkarius** [comment]
Also, it looks like that other PR I just merged in for the CCR rules has conflicts with this one.

**Comment by LexiconCode** [comment]
> 
> 
> Also, it looks like that other PR I just merged in for the CCR rules has conflicts with this one.

Should be fixed.

> 
> 
> Do those rules which print that error still work?

Will test tomorrow morning.

**Comment by LexiconCode** [comment]
> 
> 
> Do those rules which print that error still work?

Some do and some don't work for example below

It won't enable DragonRule "enable Dragon".

Interestingly with VS code it will enable the mapping VS Code grammar via `enable Visual Studio Code Non Continuous` The grammar functions as expected.

However it will not recognize `enable visual studio code continuous` as a command.

I'm not sure what's causing this behavior the only thing that DragonRule and VSCodeCcrRule is using the old style `pronunciation`.

**Comment by synkarius** [comment]
Without actually stepping through this to confirm, I have a guess as to what's going on. Try renaming either the package or the module for one of the broken rules. Doesn't really matter what you rename it to, so long as it's not the same as the module/package. So, "eclipse1.py" in the "eclipse" package for example instead of "eclipse.py" in the "eclipse" package.

**Comment by LexiconCode** [comment]
> 
> 
> Without actually stepping through this to confirm, I have a guess as to what's going on. Try renaming either the package or the module for one of the broken rules. Doesn't really matter what you rename it to, so long as it's not the same as the module/package. So, "eclipse1.py" in the "eclipse" package for example instead of "eclipse.py" in the "eclipse" package.

Your guess is correct. So renaming `"eclipse.py"` to "eclipse33.py" or tp anything else works. In addition changing the `folder` name eg `eclipse2`and not renaming any of the `.py` works as well.

**Comment by LexiconCode** [comment]
Looking at the change of imports
```
from castervoice.apps.eclipse.eclipse import EclipseCCR
from castervoice.apps.vscode.vscode import VSCodeCcrRule
```
I'm guessing the `ContentRequestGenerator` doesn't link that there's a filename and folder by the same name in the import path?

**Comment by synkarius** [comment]
That is correct. It's a flaw in the ContentRequestGenerator, or one of the closely related classes in that package. Given that the workaround is easy, let's not change that before the PR for #385 goes through.

**Comment by LexiconCode** [comment]
Ok

**Comment by synkarius** [comment]
There's a bit more cleaning up I'd like to do in the GrammarManager too, around `_delegate_enable`, but I'm also going to wait for that until the PR goes through, so we have a stable rollback point if we need it.

**Comment by LexiconCode** [comment]
Yeah sounds like a plan I'll tweak the this pull and get it updated so you can merge when you're ready.

**Comment by LexiconCode** [comment]
I'm not sure if this is directly related but this error message happens every time I change these app imports after restarting Dragon.
```
Error loading _caster from D:\Backup\Library\Documents\Caster\_caster.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 331, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "D:\Backup\Library\Documents\Caster\_caster.py", line 33, in <module>
    control.init_nexus(_content_loader)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\control.py", line 7, in init_nexus
    _NEXUS = Nexus(content_loader)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\nexus.py", line 83, in __init__
    self._load_and_register_all_content(rules_config, hooks_runner, transformers_runner)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\nexus.py", line 92, in _load_and_register_all_content
    content = self._content_loader.load_everything(rules_config)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 57, in load_everything
    rules = self._process_requests(rule_requests)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 106, in _process_requests
    content_item = self.idem_import_module(request.module_name, request.content_type)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\loading\load\content_loader.py", line 92, in idem_import_module
    return fn()
  File "D:/Backup/Library/Documents/Caster/castervoice\apps\vscode2.py", line 302, in get_rule
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\rule_details.py", line 31, in __init__
    self._filepath = RuleDetails._calculate_filepath_from_frame(stack, 1)
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\ctrl\mgr\rule_details.py", line 37, in _calculate_filepath_from_frame
    filepath = module.__file__.replace("\\", "/")
AttributeError: 'NoneType' object has no attribute '__file__'
```
I was able to fix that error message above by deleting *.pyc files from the caster product.

**Comment by LexiconCode** [comment]
This should be ready to go!

**Comment by synkarius** [comment]
That's interesting about the .pyc files. It's probably not directly related. More likely it's something that happens in general when you change imports and have .pyc files left over from prior versions. I don't know the guts of Python well enough to know how Python detects changes between .pyc files and the .py files they're compiled from. 

I can say though, that if import issues were occurring at runtime rather than boot time, the new Caster stuff should in theory be able to handle it -- not including changing paths like we are here though. If the path to the module remained unchanged, but you changed imports, the module should get recompiled to .pyc when it gets reloaded, so at the next boot, you wouldn't have issues. One thing I specifically did not tackle, for the sake of time, was loading new modules, reloading moved/renamed modules, or unloading deleted modules. All the reloading stuff currently assumes that whatever modules are loaded in at boot time are the only modules which will be available until the next full reboot, and that their paths will not change.

It doesn't have to be that way, of course. But progress comes in steps, and getting stuff reloading at all was enough of a project as it was.

**Comment by synkarius** [comment]
Manual testing looks good.

**Pull request merged**
