### PR TITLE
switch actions to caster

### PR DESCRIPTION
**Pull request by kendonB**
Addresses #30

### CODE REVIEW

**Comment by LexiconCode** [comment]
One addition would be `Key` in `dragon_support.py`. the reason it doesn't trigger a syntax error is because it's embedded in `fix_dragon_double()` function.

**Comment by kendonB** [comment]
Added that one too. Good catch

**Comment by LexiconCode** [comment]
One other bit is I believe `sample.py` should remain pure dragonfly. It should not have any caster imports or features as it's used for testing purposes.

Looks like historically `from castervoice.lib.merge.additions import IntegerRefST` Sneaked in as well.

**Comment by synkarius** [comment]
Thank you @kendonB.

**Pull request merged**
