### PR TITLE
Fix Legion not appearing in the foreground

### PR DESCRIPTION
**Pull request by gerrish**
This is an experimental Fix for the aforementioned issue. Requires testing.

### CODE REVIEW

**Comment by LexiconCode** [comment]
I have not experienced this issue so I'll need a little guidance for testing.  Is there reliable method to reproduce the bug?

**Comment by gerrish** [comment]
I haven't found any reliable way to reproduce it however it happens way too often to ignore. It seems to happen more often when I switch between apps.
Specifically the bug is that Legion opens up but in the background so the commands don't work.

**Comment by LexiconCode** [comment]
Yeah that sounds fairly annoying. The patch seems to function as expected on my end but then again I really haven't experienced the issue. Unless you have some outstanding concerns I think we should just merge it. Unless someone else experiences this issue often enough to contribute to testing.

**Comment by gerrish** [comment]
Ironically, while it seemed to work everywhere, one page in chromewith POP ups seems to have triggered the same behavior. I will just use the fix suggested in the issue instead.

**Pull request closed without merging**
