### PR TITLE
add ccr types and remove names

### PR DESCRIPTION
**Pull request by kendonB**
I'm not so sure that all of these rules really should be MergeRules but this fixes the errors for now

### CODE REVIEW

**Comment by kendonB** [comment]
Fixes #32

**Comment by LexiconCode** [comment]
With the exception of those that are meant to be CCR like `vscode`, I think it there meant to be mapping rules.

Something slightly related `vscode`should probably be renamed to `vscode_ccr` and `vscode2`to `vscode`.

**Comment by LexiconCode** [comment]
This brings up another interesting question is there a difference bet ween the following.
```
class SpellingWindowRule(MappingRule):
    pronunciation = "dragon spelling window"
```

`RuleDetails(name="dragon spelling window", executable="natspeak")`

What's the recommended approach for naming a rule?

**Comment by synkarius** [comment]
@LexiconCode That is correct about those rules not being MergeRules. This pull request is not, in my opinion, the correct solution. The correct solution is to change most of these rejected rules to MappingRules.

As for naming rules, MappingRules do not need pronunciations. It kind of begs the question as to whether MergeRules do actually, or if they'd be better off just having names as their "triggers" as well.

**Comment by kendonB** [comment]
Do `names` have any role other than to be used as what you say when enabling? If so, it seems like there's no need for a pronunciation property

**Comment by synkarius** [comment]
@kendonB In Caster, no, they do not. I agree that `pronunciation` is kind of useless now. I will remove it once this PR gets resolved.

**Comment by LexiconCode** [comment]
@kendonB would you like me to open up a new pull request with the changes or would you update this one?

**Comment by kendonB** [comment]
Hi, I'm away for the next 24 hours so please feel free to PR on this PR
branch or make a new one

>

**Comment by kendonB** [comment]
What should `BaseSelfModifyingRule` inherit from? We currently have `MergeRule` -> `BaseSelfModifyingRule` -> `BaseAliasRule` -> `Alias` where `Alias` is not intended to be CCR. 

However, we also have `MergeRule` -> `BaseSelfModifyingRule` -> `BaseAliasRule` -> `ChainAlias` so should we have a separate `BaseSelfModifyingRule` and `BaseAliasRule` that come from a `MappingRule`?

**Comment by kendonB** [comment]
My previous question is also important for the Bring me rule. I just got a misrecognition because this rule is now CCR. I think that bring me should be a `MappingRule` by default

**Comment by synkarius** [comment]
@kendonB That's a great question. My choice to split MergeRule off from MappingRule meant that there could be no more non-ccr selfmod rules, which would have been a huge loss. As much as I'd like to have kept that split, I reverted it, and then added more validations around `get_rule` as a second-best.

**Comment by synkarius** [comment]
Also, I fixed this tonight in af00792, so closing this.

**Comment by kendonB** [comment]
@synkarius How does the non-ccr MergeRule work now? Is it just assumed non-ccr if `ccrtype` isn't passed in `RuleDetails`?

**Pull request closed without merging**
