### PR TITLE
`kill_grids_and_wait()` doesn't take a parameter

### PR DESCRIPTION
**Pull request by Versatilus**
`kill_grids_and_wait()` was causing an error in `mouse_click()` because
it was being called with a parameter that wasn't necessary anymore.

### CODE REVIEW

**Comment by alexboche** [comment]
I was experiencing this error as well. Eric's change fixes it.

**Comment by Versatilus** [comment]
@synkarius Due to my workflow, I will be able to work on the codebase more if this is addressed. I need things to mostly work so I can more easily make multiple small pull requests.

**Comment by synkarius** [comment]
@Versatilus Thank you. I'll try to be more responsive to pull requests.

**Comment by synkarius** [comment]
My apologies about the delay.

**Pull request merged**
