### PR TITLE
VS Code and JavaScript CCR fixes

### PR DESCRIPTION
**Pull request by Versatilus**
I was looking through the repository of @betaorbust and I thought these commits would be a good fit for the main repository. I see no problem with merging the module for VS Code, but I thought I would seek comments from others on the changes to JavaScript CCR.

I would've just cherry picked the changes for VS Code, but I'm still feeling my way through GitHub and trying to make sure proper attribution is given. Besides, I figured it might be considered rude to merge someone else's work without explicit permission.

### CODE REVIEW

**Comment by LexiconCode** [comment]
Nice, I was just about to make my own CS Code module. I don't have any opinions on the JavaScript CCR changes.

**Comment by betaorbust** [comment]
Hey folks, 
I'd be super happy to contribute back to the project. I know it's only an ego thing, but if you don't mind too much, I'll put in a PR for these 😄 I've been holding off because it's not a complete set, but I'm entirely up for putting it in now if it'll help people out.

I'll drop one PR for each, so one won't block the other.

**Comment by betaorbust** [comment]
Oops! I see that you pulled my commits directly! That's awesome -- merge away when you feel ready 😄

**Comment by Versatilus** [comment]
My git-fu is still a bit weak and I'm ultra-paranoid about making sure credit is given properly. I'm trying to proceed cautiously.

This is one of those projects where I get the sense quite a few people fork the repository and start making dramatic customizations. This makes me a little nervous about making sure changes are easy for others to either integrate or ignore.

**Pull request merged**
