### PR TITLE
Add an initial draft of R, Matlab CCR grammars

### PR DESCRIPTION
**Pull request by shippy**
Belated PR that adds some statistical computing languages. I'm filing this PR in part to figure out if there are any standards I should be observing -- see especially the R file, which goes beyond "core" shared elements between languages.

### CODE REVIEW

**Comment by LexiconCode** [comment]
@shippy I'm fine with that going beyond the core elements.  I will merge in two days if there's no input from the rest of the team.

**Comment by gerrish** [comment]
Aren't tokensets a deprecated feature?

**Comment by LexiconCode** [comment]
https://github.com/synkarius/caster/issues/192
Correct

**Comment by shippy** [comment]
Excellent; I was cargo-culting those and I'm happy to them out.

**Comment by LexiconCode** [comment]
@shippy Awesome when that's done we'll get it merged!

**Comment by LexiconCode** [comment]
@shippy for some reason I can't get your grammars to enable or disable. Can you reproduce on your end?

**Comment by gerrish** [comment]
The classes must be added to init.

**Comment by LexiconCode** [comment]
I'd forgotten about that. We need to add that to the documentation.

**Comment by mrob95** [comment]
I've updated this with the following:
* Updated init and removed references to TokenSet.
* Removed R functions which were duplicating core functions eg punctuation.
* Updated "convert" and "import" functions to better match R syntax.
* Added commonly used functions from the dplyr and tidyr packages.
Will commit when I can.

**Comment by LexiconCode** [comment]
@shippy @mrob95 
I'm going to merge shippy's pull request and then mrob95 create a new pull request with your enhancement.

**Comment by shippy** [comment]
@mrob95 Thank you for finishing this!

**Pull request merged**
